# Generated by Django 4.0 on 2024-02-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('low', 'Low')], default='Not Specified', max_length=100),
        ),
    ]
