# Generated by Django 4.0 on 2024-02-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('management', '0004_alter_taskmodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='assigned_by',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='auth.user'),
        ),
    ]
